/**
 * SpecKit Templates
 *
 * 默认模板加载和管理
 */

import { readFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

// ============================================================================
// 常量
// ============================================================================

const __dirname = dirname(fileURLToPath(import.meta.url));

const TEMPLATE_PATHS = {
  constitution: join(__dirname, 'constitution-template.md'),
  spec: join(__dirname, 'spec-template.md'),
  plan: join(__dirname, 'plan-template.md'),
  tasks: join(__dirname, 'tasks-template.md'),
} as const;

export type TemplateName = keyof typeof TEMPLATE_PATHS;

// ============================================================================
// 类型定义
// ============================================================================

/**
 * 模板变量
 */
export type TemplateVariables = Record<string, string | number | boolean | undefined>;

// ============================================================================
// 内置模板（fallback）
//
// 说明：
// - 仓库内 CLI 场景通常直接从源码目录读取模板文件即可。
// - 为了避免未来 build/打包后模板文件不在同路径导致 loadTemplate 失败，这里提供内置 fallback。
// ============================================================================

const DEFAULT_TEMPLATES: Record<TemplateName, string> = {
  constitution: [
    '# Project Constitution',
    '',
    '> This document establishes the foundational principles and guidelines for the project.',
    '',
    '## Core Principles',
    '',
    '- **Quality First**: Prioritize code quality over speed of delivery',
    '- **Test-Driven Development**: Write tests before implementation when possible',
    '- **Documentation as Code**: Keep documentation in sync with code changes',
    '- **Simplicity**: Prefer simple solutions over complex abstractions',
    '- **Consistency**: Follow established patterns throughout the codebase',
    '',
    '## Code Quality Guidelines',
    '',
    '### Code Style',
    '',
    '- Use consistent formatting (Prettier recommended)',
    '- Follow language-specific idioms and best practices',
    '- Keep functions/methods focused on a single responsibility',
    '- Limit line length to improve readability',
    '',
    '### Naming Conventions',
    '',
    '- Use descriptive, meaningful names for variables and functions',
    '- Follow camelCase for variables/functions, PascalCase for classes/types',
    '- Use UPPER_CASE for constants',
    '- Prefix boolean variables with `is`, `has`, `should`, etc.',
    '',
    '### Documentation Requirements',
    '',
    '- Document public APIs with JSDoc/TSDoc comments',
    '- Include usage examples for complex functions',
    '- Keep README up-to-date with setup instructions',
    '- Add inline comments for non-obvious logic',
    '',
    '### Error Handling',
    '',
    '- Use typed errors when possible',
    '- Provide meaningful error messages',
    '- Log errors with sufficient context for debugging',
    '- Fail fast and explicitly',
    '',
    '## Testing Standards',
    '',
    '### Coverage Requirements',
    '',
    '- Aim for 80%+ code coverage for critical paths',
    '- 100% coverage for utility functions and data transformations',
    '- Focus on behavior, not implementation details',
    '',
    '### Test Types',
    '',
    '- **Unit Tests**: Test individual functions and components',
    '- **Integration Tests**: Test component interactions',
    '- **E2E Tests**: Test critical user flows',
    '',
    '### TDD Approach',
    '',
    '1. Write a failing test first',
    '2. Write minimal code to pass the test',
    '3. Refactor while keeping tests green',
    '',
    '## UX Consistency Guidelines',
    '',
    '### Design Principles',
    '',
    '- Mobile-first responsive design',
    '- Consistent spacing and typography',
    '- Clear visual hierarchy',
    '- Accessible color contrast',
    '',
    '### Accessibility Requirements',
    '',
    '- Support keyboard navigation',
    '- Provide ARIA labels for interactive elements',
    '- Ensure color is not the only indicator',
    '- Support screen readers',
    '',
    '### Responsiveness',
    '',
    '- Breakpoints: mobile (< 768px), tablet (768-1024px), desktop (> 1024px)',
    '- Fluid layouts with max-width containers',
    '- Touch-friendly interactive elements (min 44x44px)',
    '',
    '## Performance Requirements',
    '',
    '### Load Time Targets',
    '',
    '- First Contentful Paint: < 1.5s',
    '- Time to Interactive: < 3s',
    '- Largest Contentful Paint: < 2.5s',
    '',
    '### Memory Limits',
    '',
    '- Avoid memory leaks in long-running processes',
    '- Clean up event listeners and subscriptions',
    '- Use pagination/virtualization for large datasets',
    '',
    '### Optimization Strategies',
    '',
    '- Lazy load non-critical resources',
    '- Optimize images and assets',
    '- Use code splitting for large bundles',
    '- Cache API responses appropriately',
    '',
  ].join('\n'),
  spec: [
    '# {{FEATURE_NAME}}',
    '',
    '> {{BRIEF_DESCRIPTION}}',
    '',
    '## Overview',
    '',
    '{{DETAILED_DESCRIPTION}}',
    '',
    '## User Stories',
    '',
    '### US-001: {{USER_STORY_TITLE}}',
    '',
    'As a {{USER_TYPE}}, I want {{GOAL}} so that {{BENEFIT}}.',
    '',
    '**Priority:** {{PRIORITY}}',
    '',
    '**Acceptance Criteria:**',
    '',
    '- [ ] {{CRITERION_1}}',
    '- [ ] {{CRITERION_2}}',
    '- [ ] {{CRITERION_3}}',
    '',
    '### US-002: {{USER_STORY_TITLE}}',
    '',
    'As a {{USER_TYPE}}, I want {{GOAL}} so that {{BENEFIT}}.',
    '',
    '**Priority:** {{PRIORITY}}',
    '',
    '**Acceptance Criteria:**',
    '',
    '- [ ] {{CRITERION_1}}',
    '- [ ] {{CRITERION_2}}',
    '',
    '## Acceptance Criteria',
    '',
    'Global acceptance criteria that apply to the entire feature:',
    '',
    '- [ ] All user stories are implemented and tested',
    '- [ ] Documentation is updated',
    '- [ ] Performance requirements are met',
    '- [ ] Accessibility requirements are met',
    '- [ ] Cross-browser/device compatibility verified',
    '',
    '## Out of Scope',
    '',
    'The following items are explicitly NOT part of this specification:',
    '',
    '- {{OUT_OF_SCOPE_ITEM_1}}',
    '- {{OUT_OF_SCOPE_ITEM_2}}',
    '',
    '## Data Model',
    '',
    '### {{ENTITY_NAME}}',
    '',
    '{{ENTITY_DESCRIPTION}}',
    '',
    '| Field          | Type           | Required     | Description           |',
    '| -------------- | -------------- | ------------ | --------------------- |',
    '| id             | string         | Yes          | Unique identifier     |',
    '| {{FIELD_NAME}} | {{FIELD_TYPE}} | {{REQUIRED}} | {{FIELD_DESCRIPTION}} |',
    '| createdAt      | timestamp      | Yes          | Creation timestamp    |',
    '| updatedAt      | timestamp      | Yes          | Last update timestamp |',
    '',
    '**Relationships:**',
    '',
    '- {{ENTITY_NAME}} has many {{RELATED_ENTITY}}',
    '',
    '## Non-Functional Requirements',
    '',
    '### Performance',
    '',
    '- {{PERFORMANCE_REQUIREMENT}}',
    '',
    '### Security',
    '',
    '- {{SECURITY_REQUIREMENT}}',
    '',
    '### Scalability',
    '',
    '- {{SCALABILITY_REQUIREMENT}}',
    '',
    '---',
    '',
    '_Last updated: {{DATE}}_ _Status: Draft | In Review | Approved_',
    '',
  ].join('\n'),
  plan: [
    '# Implementation Plan: {{FEATURE_NAME}}',
    '',
    '> Technical implementation plan for {{SPEC_ID}}',
    '',
    '## Technology Stack',
    '',
    '| Component | Technology   | Version     |',
    '| --------- | ------------ | ----------- |',
    '| Runtime   | {{RUNTIME}}  | {{VERSION}} |',
    '| Frontend  | {{FRONTEND}} | {{VERSION}} |',
    '| Backend   | {{BACKEND}}  | {{VERSION}} |',
    '| Database  | {{DATABASE}} | {{VERSION}} |',
    '| Testing   | {{TESTING}}  | {{VERSION}} |',
    '',
    '### Dependencies',
    '',
    'Core dependencies for this feature:',
    '',
    '- `{{PACKAGE_1}}` - {{DESCRIPTION}}',
    '- `{{PACKAGE_2}}` - {{DESCRIPTION}}',
    '',
    '### Dev Dependencies',
    '',
    '- `{{DEV_PACKAGE_1}}` - {{DESCRIPTION}}',
    '',
    '## Architecture',
    '',
    '**Pattern:** {{ARCHITECTURE_PATTERN}}',
    '',
    '### Key Decisions',
    '',
    '- {{DECISION_1}}',
    '- {{DECISION_2}}',
    '',
    '### Constraints',
    '',
    '- {{CONSTRAINT_1}}',
    '- {{CONSTRAINT_2}}',
    '',
    '### Directory Structure',
    '',
    '```',
    'src/',
    '├── {{MODULE}}/',
    '│   ├── components/',
    '│   │   └── {{Component}}.tsx',
    '│   ├── hooks/',
    '│   │   └── use{{Hook}}.ts',
    '│   ├── services/',
    '│   │   └── {{service}}.ts',
    '│   ├── types.ts',
    '│   └── index.ts',
    '└── ...',
    '```',
    '',
    '## Implementation Phases',
    '',
    '### Phase 1: Project Setup',
    '',
    '**Estimated:** 2 hours',
    '',
    'Initialize project structure and core dependencies.',
    '',
    '**Steps:**',
    '',
    '1. Create project structure',
    '2. Install dependencies',
    '3. Configure build tools',
    '4. Set up testing framework',
    '5. Configure linting and formatting',
    '',
    '**Exit Criteria:**',
    '',
    '- [ ] Project builds without errors',
    '- [ ] Test runner works',
    '- [ ] Linting passes',
    '',
    '---',
    '',
    '### Phase 2: Core Implementation',
    '',
    '**Estimated:** {{HOURS}} hours',
    '',
    'Implement core functionality based on user stories.',
    '',
    '**Steps:**',
    '',
    '1. {{STEP_1}}',
    '2. {{STEP_2}}',
    '3. {{STEP_3}}',
    '',
    '**Exit Criteria:**',
    '',
    '- [ ] {{CRITERION_1}}',
    '- [ ] {{CRITERION_2}}',
    '',
    '---',
    '',
    '### Phase 3: Integration & Testing',
    '',
    '**Estimated:** {{HOURS}} hours',
    '',
    'Integrate components and add comprehensive tests.',
    '',
    '**Steps:**',
    '',
    '1. Write unit tests',
    '2. Write integration tests',
    '3. Perform manual testing',
    '4. Fix bugs found during testing',
    '',
    '**Exit Criteria:**',
    '',
    '- [ ] 80%+ test coverage',
    '- [ ] All acceptance criteria verified',
    '- [ ] No critical bugs',
    '',
    '---',
    '',
    '### Phase 4: Documentation & Polish',
    '',
    '**Estimated:** {{HOURS}} hours',
    '',
    'Complete documentation and final polish.',
    '',
    '**Steps:**',
    '',
    '1. Update API documentation',
    '2. Write usage examples',
    '3. Update README',
    '4. Code review and cleanup',
    '',
    '**Exit Criteria:**',
    '',
    '- [ ] Documentation complete',
    '- [ ] Code reviewed',
    '- [ ] Ready for deployment',
    '',
    '## API Contracts',
    '',
    '### {{API_NAME}}',
    '',
    '**Base URL:** `{{BASE_URL}}`',
    '',
    '| Method | Path                | Description              |',
    '| ------ | ------------------- | ------------------------ |',
    '| GET    | `/{{resource}}`     | List all {{resources}}   |',
    '| POST   | `/{{resource}}`     | Create a {{resource}}    |',
    '| GET    | `/{{resource}}/:id` | Get a {{resource}} by ID |',
    '| PUT    | `/{{resource}}/:id` | Update a {{resource}}    |',
    '| DELETE | `/{{resource}}/:id` | Delete a {{resource}}    |',
    '',
    '### Request/Response Examples',
    '',
    '```json',
    '// POST /{{resource}}',
    '{',
    '  \"{{field}}\": \"{{value}}\"',
    '}',
    '',
    '// Response',
    '{',
    '  \"id\": \"{{id}}\",',
    '  \"{{field}}\": \"{{value}}\",',
    '  \"createdAt\": \"{{timestamp}}\"',
    '}',
    '```',
    '',
    '## Research Notes',
    '',
    '### Technology Research',
    '',
    '{{RESEARCH_NOTES}}',
    '',
    '### Best Practices',
    '',
    '- {{BEST_PRACTICE_1}}',
    '- {{BEST_PRACTICE_2}}',
    '',
    '### Risks',
    '',
    '- ⚠️ {{RISK_1}}',
    '- ⚠️ {{RISK_2}}',
    '',
    '### Mitigation Strategies',
    '',
    '- {{MITIGATION_1}}',
    '- {{MITIGATION_2}}',
    '',
    '---',
    '',
    '_Plan created: {{DATE}}_ _Based on spec: {{SPEC_ID}}_',
    '',
  ].join('\n'),
  tasks: [
    '# Task Breakdown: {{FEATURE_NAME}}',
    '',
    '> Actionable tasks for implementing {{SPEC_ID}}',
    '',
    '**Total Tasks:** {{TASK_COUNT}} **Parallelizable:** {{PARALLEL_COUNT}} **Estimated Total:**',
    '{{TOTAL_HOURS}} hours',
    '',
    '---',
    '',
    '## Setup & Configuration',
    '',
    '- [ ] **task-001**: Initialize project structure Create the basic project structure with',
    '      configuration files. Files: `package.json`, `tsconfig.json`, `.gitignore` Estimated: 0.5h',
    '',
    '- [ ] **task-002**: Install core dependencies Install and configure required packages. Files:',
    '      `package.json`, `package-lock.json` Depends on: task-001 Estimated: 0.5h',
    '',
    '- [ ] **task-003**: Configure development tools [P] Set up linting, formatting, and testing tools.',
    '      Files: `.eslintrc`, `.prettierrc`, `jest.config.js` Depends on: task-001 Estimated: 1h',
    '',
    '---',
    '',
    '## Core Implementation',
    '',
    '- [ ] **task-004**: Create data types and interfaces [TDD] Define TypeScript types for the domain',
    '      model. Files: `src/types.ts`, `src/types.test.ts` Depends on: task-002 Estimated: 1h',
    '',
    '- [ ] **task-005**: Implement core service [TDD] Create the main service with business logic. Files:',
    '      `src/services/{{service}}.ts`, `src/services/{{service}}.test.ts` Depends on: task-004',
    '      Estimated: 2h',
    '',
    '- [ ] **task-006**: Create API routes Implement REST API endpoints. Files:',
    '      `src/routes/{{resource}}.ts` Depends on: task-005 Estimated: 2h',
    '',
    '---',
    '',
    '## UI Components (if applicable)',
    '',
    '- [ ] **task-007**: Create base components [P] Build reusable UI components. Files:',
    '      `src/components/Button.tsx`, `src/components/Input.tsx` Depends on: task-002 Estimated: 2h',
    '',
    '- [ ] **task-008**: Create feature components [P] Build feature-specific components. Files:',
    '      `src/components/{{Feature}}.tsx` Depends on: task-007 Estimated: 3h',
    '',
    '- [ ] **task-009**: Implement state management Set up state management for the feature. Files:',
    '      `src/store/{{feature}}.ts` Depends on: task-004 Estimated: 2h',
    '',
    '---',
    '',
    '## Integration & Testing',
    '',
    '- [ ] **task-010**: Write integration tests Create tests for component interactions. Files:',
    '      `tests/integration/*.test.ts` Depends on: task-006 Estimated: 2h',
    '',
    '- [ ] **task-011**: Write E2E tests Create end-to-end tests for critical flows. Files:',
    '      `tests/e2e/*.spec.ts` Depends on: task-010 Estimated: 2h',
    '',
    '---',
    '',
    '## Documentation',
    '',
    '- [ ] **task-012**: Update API documentation Document all API endpoints. Files: `docs/api.md`',
    '      Depends on: task-006 Estimated: 1h',
    '',
    '- [ ] **task-013**: Update README Add usage instructions and examples. Files: `README.md` Depends',
    '      on: task-012 Estimated: 0.5h',
    '',
    '---',
    '',
    '## Parallel Execution Groups',
    '',
    '**Group 1:** task-003, task-004 Setup tasks that can run in parallel after initialization.',
    '',
    '**Group 2:** task-007, task-008 UI component tasks that can run in parallel.',
    '',
    '---',
    '',
    '## Task Legend',
    '',
    '- `[P]` - Parallelizable: Can be executed concurrently with other parallel tasks',
    '- `[TDD]` - Test-Driven: Write tests before implementation',
    '- `Depends on:` - Must wait for specified tasks to complete',
    '',
    '---',
    '',
    '_Generated: {{DATE}}_ _Based on plan: {{PLAN_ID}}_',
    '',
  ].join('\n'),
};

// ============================================================================
// 函数
// ============================================================================

/**
 * 加载模板内容
 */
export async function loadTemplate(name: TemplateName): Promise<string> {
  const path = TEMPLATE_PATHS[name];
  try {
    return await readFile(path, 'utf-8');
  } catch {
    return DEFAULT_TEMPLATES[name];
  }
}

/**
 * 替换模板变量
 *
 * 变量格式: {{VARIABLE_NAME}}
 */
export function renderTemplate(template: string, variables: TemplateVariables): string {
  let result = template;

  for (const [key, value] of Object.entries(variables)) {
    if (value !== undefined) {
      const regex = new RegExp(`\\{\\{${key}\\}\\}`, 'g');
      result = result.replace(regex, String(value));
    }
  }

  return result;
}

/**
 * 加载并渲染模板
 */
export async function loadAndRenderTemplate(
  name: TemplateName,
  variables: TemplateVariables
): Promise<string> {
  const template = await loadTemplate(name);
  return renderTemplate(template, variables);
}

/**
 * 获取所有可用模板名称
 */
export function getAvailableTemplates(): TemplateName[] {
  return Object.keys(TEMPLATE_PATHS) as TemplateName[];
}

/**
 * 检查模板是否存在
 */
export function hasTemplate(name: string): name is TemplateName {
  return name in TEMPLATE_PATHS;
}
