/**
 * 本地沙盒驱动
 *
 * 提供无 Docker 依赖的本地沙盒实现，用于开发和测试
 *
 * ⚠️ 警告：此驱动仅供开发/测试使用，生产环境应使用 Docker 驱动
 *
 * 特性：
 * - 使用 Bun.spawn 执行命令
 * - 限制工作目录（带符号链接保护）
 * - 基础超时控制
 * - 可选命令白名单安全限制（带 shell 元字符检测）
 * - 子进程跟踪和清理
 *
 * 安全特性：
 * - realpath 解析防止符号链接绕过
 * - shell 元字符检测防止命令注入
 * - 安全路径验证防止危险的 rm -rf
 * - 唯一文件名防止并发竞态
 */

import { mkdir, rm, readFile, writeFile, readdir, access, realpath, lstat } from 'node:fs/promises';
import { join, resolve, relative, isAbsolute, dirname, basename } from 'node:path';
import { tmpdir } from 'node:os';
import { randomUUID } from 'node:crypto';
import { BaseSandbox, TimeoutError } from '../base';
import type {
  SandboxConfig,
  ExecutionOptions,
  ExecutionResult,
  CommandResult,
  LocalRuntimeConfig,
} from '../types';

// ============================================================================
// 常量定义
// ============================================================================

/** 默认 Shell 路径 */
const DEFAULT_SHELL = process.platform === 'win32' ? 'cmd.exe' : '/bin/sh';

/**
 * Shell 危险元字符正则表达式（用于检测命令注入）
 *
 * 检测的危险字符：
 * - ; - 命令分隔符
 * - & - 后台执行 / AND 运算符
 * - | - 管道 / OR 运算符
 * - ` - 命令替换（反引号）
 * - $( - 命令替换
 * - ${ - 变量替换
 * - < > - 重定向
 * - \n \r - 换行符（允许通过换行注入命令）
 *
 * 注意：引号（' "）是允许的，用于正常的参数引用
 */
const SHELL_METACHAR_REGEX = /[;&|`<>\n\r]|\$[({]/;

/** 安全的工作目录基础路径（默认为系统临时目录） */
const SAFE_WORKDIR_BASES = [
  tmpdir(),
  '/tmp',
  '/var/tmp',
];

/** 沙盒目录前缀 */
const SANDBOX_DIR_PREFIX = 'local-sandbox-';

// ============================================================================
// 自定义错误类型
// ============================================================================

/**
 * 命令不允许错误
 *
 * 当执行的命令不在白名单中时抛出
 */
export class CommandNotAllowedError extends Error {
  /** 被禁止的命令 */
  readonly command: string;

  constructor(command: string) {
    super(`Command not allowed: ${command}`);
    this.name = 'CommandNotAllowedError';
    this.command = command;
  }
}

/**
 * 命令注入检测错误
 *
 * 当命令包含危险的 shell 元字符时抛出
 */
export class CommandInjectionError extends Error {
  /** 检测到的命令 */
  readonly command: string;

  constructor(command: string) {
    super(`Potential command injection detected: ${command}`);
    this.name = 'CommandInjectionError';
    this.command = command;
  }
}

/**
 * 路径越界错误
 *
 * 当访问的路径超出工作目录范围时抛出
 */
export class PathOutOfBoundsError extends Error {
  /** 尝试访问的路径 */
  readonly path: string;

  constructor(path: string) {
    super(`Path is outside of sandbox workspace: ${path}`);
    this.name = 'PathOutOfBoundsError';
    this.path = path;
  }
}

/**
 * 符号链接不允许错误
 *
 * 当路径包含指向工作目录外的符号链接时抛出
 */
export class SymlinkNotAllowedError extends Error {
  /** 符号链接路径 */
  readonly path: string;

  constructor(path: string) {
    super(`Symlink pointing outside workspace not allowed: ${path}`);
    this.name = 'SymlinkNotAllowedError';
    this.path = path;
  }
}

/**
 * 不安全的工作目录错误
 *
 * 当工作目录配置不安全时抛出
 */
export class UnsafeWorkdirError extends Error {
  /** 不安全的路径 */
  readonly path: string;

  constructor(path: string) {
    super(`Unsafe workdir configuration: ${path}. Workdir must be under a safe base directory and contain sandbox ID.`);
    this.name = 'UnsafeWorkdirError';
    this.path = path;
  }
}

// ============================================================================
// LocalSandbox 实现
// ============================================================================

/**
 * 本地沙盒实现
 *
 * 使用 Bun.spawn 直接执行命令，无需 Docker 依赖
 * 仅用于开发和测试环境
 *
 * @example
 * ```ts
 * const config = createSandboxConfig({
 *   runtime: 'local',
 *   timeout: 30000,
 *   runtimeConfig: {
 *     shell: '/bin/bash',
 *     inheritEnv: false,
 *     allowedCommands: ['node', 'npm', 'bun'],
 *   },
 * });
 *
 * const sandbox = new LocalSandbox('dev-sandbox-001', config);
 * await sandbox.initialize();
 *
 * const result = await sandbox.runCommand('echo "Hello"');
 * console.log(result.stdout); // "Hello"
 *
 * await sandbox.destroy();
 * ```
 */
export class LocalSandbox extends BaseSandbox {
  /** 工作目录路径 */
  private workdir: string;

  /** 工作目录的真实路径（realpath 解析后） */
  private realWorkdir: string | null = null;

  /** 本地运行时配置 */
  private localConfig: LocalRuntimeConfig;

  /** 是否已清理 */
  private cleaned = false;

  /** 活跃的子进程集合（用于清理） */
  private activeProcesses = new Set<{ kill: () => void; pid?: number }>();

  /** 是否使用自动生成的工作目录 */
  private autoGeneratedWorkdir: boolean;

  constructor(id: string | undefined, config: SandboxConfig) {
    super(id, config);

    // 获取本地运行时配置
    this.localConfig = (config.runtimeConfig as LocalRuntimeConfig) || {};

    // 设置工作目录（使用配置的或创建临时目录）
    if (config.filesystem?.workdir) {
      this.workdir = resolve(config.filesystem.workdir);
      this.autoGeneratedWorkdir = false;
    } else {
      this.workdir = join(tmpdir(), `${SANDBOX_DIR_PREFIX}${this.id}`);
      this.autoGeneratedWorkdir = true;
    }
  }

  // ==========================================================================
  // 公共方法
  // ==========================================================================

  /**
   * 获取工作目录路径
   */
  getWorkdir(): string {
    return this.workdir;
  }

  // ==========================================================================
  // 保护方法实现
  // ==========================================================================

  /**
   * 初始化本地沙盒
   *
   * 创建工作目录并验证安全性
   */
  protected async doInitialize(): Promise<void> {
    // 验证工作目录安全性（仅对自动生成的目录或用户配置的目录）
    this.validateWorkdirSafety();

    // 创建工作目录
    await mkdir(this.workdir, { recursive: true });

    // 获取工作目录的真实路径
    this.realWorkdir = await realpath(this.workdir);

    // 记录警告：仅用于开发/测试
    console.warn(
      `[LocalSandbox ${this.id}] ⚠️ Local sandbox is for development/testing only. ` +
      'Use Docker sandbox for production environments.'
    );

    // 网络模式警告
    if (this.config.network.mode === 'full') {
      console.warn(
        `[LocalSandbox ${this.id}] ⚠️ Network mode is 'full'. ` +
        'Local sandbox does not enforce network restrictions.'
      );
    }
  }

  /**
   * 执行代码
   *
   * 将代码写入唯一临时文件，然后使用 Bun 执行
   * 使用 UUID 文件名防止并发竞态条件
   */
  protected async doExecute(code: string, options?: ExecutionOptions): Promise<ExecutionResult> {
    const startTime = Date.now();

    // 使用唯一文件名防止并发竞态
    const uniqueId = randomUUID();
    const codeFile = join(this.workdir, `_code_${uniqueId}.ts`);

    await writeFile(codeFile, code, 'utf-8');

    try {
      // 使用 bun run 执行代码（使用当前进程的 Bun 路径）
      const bunPath = process.execPath;
      const result = await this.spawnProcess(
        [bunPath, 'run', codeFile],
        options
      );

      return {
        ...result,
        duration: Date.now() - startTime,
      };
    } finally {
      // 清理临时代码文件
      try {
        await rm(codeFile, { force: true });
      } catch {
        // 忽略清理失败
      }
    }
  }

  /**
   * 运行命令
   *
   * 使用 Shell 执行命令，带命令注入检测
   */
  protected async doRunCommand(command: string, options?: ExecutionOptions): Promise<CommandResult> {
    const startTime = Date.now();

    // 验证命令安全性（白名单 + 元字符检测）
    this.validateCommand(command);

    const shell = this.localConfig.shell || DEFAULT_SHELL;
    const shellArgs = process.platform === 'win32'
      ? ['/c', command]
      : ['-c', command];

    const result = await this.spawnProcess(
      [shell, ...shellArgs],
      options
    );

    return {
      ...result,
      command,
      duration: Date.now() - startTime,
    };
  }

  /**
   * 写入文件
   */
  protected async doWriteFile(path: string, content: string): Promise<void> {
    const fullPath = this.resolvePath(path);
    await this.validatePathWithRealpath(fullPath);

    // 确保父目录存在
    const parentDir = dirname(fullPath);
    await mkdir(parentDir, { recursive: true });

    await writeFile(fullPath, content, 'utf-8');
  }

  /**
   * 读取文件
   */
  protected async doReadFile(path: string): Promise<string> {
    const fullPath = this.resolvePath(path);
    await this.validatePathWithRealpath(fullPath);

    return readFile(fullPath, 'utf-8');
  }

  /**
   * 检查文件是否存在
   */
  protected async doFileExists(path: string): Promise<boolean> {
    const fullPath = this.resolvePath(path);

    try {
      await this.validatePathWithRealpath(fullPath);
      await access(fullPath);
      return true;
    } catch {
      return false;
    }
  }

  /**
   * 列出目录内容
   */
  protected async doListDir(path: string): Promise<string[]> {
    const fullPath = this.resolvePath(path);
    await this.validatePathWithRealpath(fullPath);

    return readdir(fullPath);
  }

  /**
   * 销毁沙盒
   *
   * 终止所有活跃进程并清理工作目录
   */
  protected async doDestroy(): Promise<void> {
    if (this.cleaned) {
      return;
    }

    // 终止所有活跃的子进程
    const processes = Array.from(this.activeProcesses);
    for (const proc of processes) {
      try {
        proc.kill();
      } catch {
        // 忽略终止失败（进程可能已退出）
      }
    }
    this.activeProcesses.clear();

    // 验证工作目录安全性再删除
    if (!this.isWorkdirSafeToDelete()) {
      console.error(
        `[LocalSandbox ${this.id}] ⚠️ Refusing to delete potentially unsafe workdir: ${this.workdir}`
      );
      this.cleaned = true;
      return;
    }

    try {
      // 删除整个工作目录
      await rm(this.workdir, { recursive: true, force: true });
      this.cleaned = true;
    } catch (error) {
      console.warn(
        `[LocalSandbox ${this.id}] Failed to clean up workdir: ${this.workdir}`,
        error
      );
    }
  }

  // ==========================================================================
  // 私有方法
  // ==========================================================================

  /**
   * 解析路径
   *
   * 将相对路径解析为相对于工作目录的绝对路径
   */
  private resolvePath(path: string): string {
    if (isAbsolute(path)) {
      return path;
    }
    return resolve(this.workdir, path);
  }

  /**
   * 验证路径是否在工作目录内（使用 realpath 防止符号链接绕过）
   *
   * @throws {PathOutOfBoundsError} 路径超出工作目录
   * @throws {SymlinkNotAllowedError} 符号链接指向工作目录外
   */
  private async validatePathWithRealpath(fullPath: string): Promise<void> {
    // 确保有真实工作目录路径
    if (!this.realWorkdir) {
      throw new Error('Sandbox not initialized');
    }

    // 首先做基础路径检查（快速失败）
    // 注意：在 macOS 上 /var 是 /private/var 的符号链接
    // 所以我们需要同时使用 this.workdir（逻辑路径）进行基础检查
    const normalizedPath = resolve(fullPath);

    // 用逻辑路径（workdir）做基础检查，避免 macOS 符号链接问题
    const logicalRelative = relative(resolve(this.workdir), normalizedPath);
    if (logicalRelative.startsWith('..') || isAbsolute(logicalRelative)) {
      throw new PathOutOfBoundsError(fullPath);
    }

    // 检查路径是否存在
    let pathExists = false;
    try {
      await access(fullPath);
      pathExists = true;
    } catch {
      // 文件不存在，只做基础检查（写入新文件的情况）
      return;
    }

    // 如果路径存在，进行更严格的符号链接检查
    if (pathExists) {
      // 检查是否是符号链接
      const stat = await lstat(fullPath);
      if (stat.isSymbolicLink()) {
        // 获取符号链接的真实目标
        const realTarget = await realpath(fullPath);
        const targetRelative = relative(this.realWorkdir, realTarget);

        // 如果真实目标在工作目录外，拒绝
        if (targetRelative.startsWith('..') || isAbsolute(targetRelative)) {
          throw new SymlinkNotAllowedError(fullPath);
        }
      }

      // 使用 realpath 验证最终路径
      try {
        const realFullPath = await realpath(fullPath);
        const finalRelative = relative(this.realWorkdir, realFullPath);

        if (finalRelative.startsWith('..') || isAbsolute(finalRelative)) {
          throw new PathOutOfBoundsError(fullPath);
        }
      } catch (error) {
        if (error instanceof PathOutOfBoundsError || error instanceof SymlinkNotAllowedError) {
          throw error;
        }
        // realpath 失败可能是其他原因，忽略
      }
    }
  }

  /**
   * 验证工作目录配置的安全性
   *
   * 确保工作目录在安全的基础路径下，防止误删系统重要目录
   */
  private validateWorkdirSafety(): void {
    const normalizedWorkdir = resolve(this.workdir);

    // 检查是否是危险路径
    const dangerousPaths = ['/', '/tmp', '/var', '/etc', '/usr', '/home', '/root', tmpdir()];
    if (dangerousPaths.includes(normalizedWorkdir)) {
      throw new UnsafeWorkdirError(normalizedWorkdir);
    }

    // 如果是自动生成的目录，检查是否包含沙盒前缀
    if (this.autoGeneratedWorkdir) {
      const dirName = basename(normalizedWorkdir);
      if (!dirName.startsWith(SANDBOX_DIR_PREFIX)) {
        throw new UnsafeWorkdirError(normalizedWorkdir);
      }
    }

    // 如果是用户配置的目录，验证路径看起来合理
    if (!this.autoGeneratedWorkdir) {
      // 检查是否在安全基础路径下
      const isUnderSafeBase = SAFE_WORKDIR_BASES.some(base => {
        const rel = relative(base, normalizedWorkdir);
        return !rel.startsWith('..') && !isAbsolute(rel) && rel.length > 0;
      });

      // 如果不在安全基础路径下，至少确保路径深度足够（防止 /home, /var 等）
      const pathDepth = normalizedWorkdir.split('/').filter(Boolean).length;
      if (!isUnderSafeBase && pathDepth < 3) {
        console.warn(
          `[LocalSandbox ${this.id}] ⚠️ Workdir "${normalizedWorkdir}" may not be safe. ` +
          'Consider using a path under /tmp or a dedicated sandbox directory.'
        );
      }
    }
  }

  /**
   * 检查工作目录是否安全删除
   *
   * 防止误删系统重要目录
   */
  private isWorkdirSafeToDelete(): boolean {
    const normalizedWorkdir = resolve(this.workdir);

    // 绝对不能删除的路径
    const forbiddenPaths = ['/', '/tmp', '/var', '/etc', '/usr', '/home', '/root', tmpdir()];
    if (forbiddenPaths.includes(normalizedWorkdir)) {
      return false;
    }

    // 自动生成的目录必须包含沙盒前缀和 ID
    if (this.autoGeneratedWorkdir) {
      const dirName = basename(normalizedWorkdir);
      return dirName.startsWith(SANDBOX_DIR_PREFIX) && dirName.includes(this.id);
    }

    // 用户配置的目录需要更严格的检查
    // 路径深度必须 >= 3（如 /tmp/sandbox/my-dir）
    const pathDepth = normalizedWorkdir.split('/').filter(Boolean).length;
    return pathDepth >= 3;
  }

  /**
   * 验证命令安全性
   *
   * 检查命令白名单和 shell 元字符注入
   *
   * @throws {CommandNotAllowedError} 命令不在白名单中
   * @throws {CommandInjectionError} 检测到潜在命令注入
   */
  private validateCommand(command: string): void {
    const allowedCommands = this.localConfig.allowedCommands;
    const trimmedCommand = command.trim();

    // 检查 shell 元字符（命令注入检测）
    if (allowedCommands && allowedCommands.length > 0) {
      // 有白名单时，检测危险元字符
      if (SHELL_METACHAR_REGEX.test(trimmedCommand)) {
        throw new CommandInjectionError(trimmedCommand);
      }
    }

    // 白名单检查
    if (!allowedCommands || allowedCommands.length === 0) {
      // 未配置白名单，允许所有命令（仅限开发/测试环境）
      // 生产环境应配置 allowedCommands 限制可执行命令
      return;
    }

    // 提取命令的第一个词（程序名）
    const firstWord = trimmedCommand.split(/\s+/)[0];
    const commandName = firstWord ?? trimmedCommand;

    // 检查是否在白名单中
    const isAllowed = allowedCommands.some(allowed => {
      // 支持完整路径或命令名匹配
      return commandName === allowed || commandName.endsWith(`/${allowed}`);
    });

    if (!isAllowed) {
      throw new CommandNotAllowedError(commandName);
    }
  }

  /**
   * 构建环境变量
   */
  private buildEnv(options?: ExecutionOptions): Record<string, string> {
    const baseEnv = this.localConfig.inheritEnv
      ? { ...process.env }
      : {};

    return {
      ...baseEnv,
      ...this.config.env,
      ...options?.env,
      // 设置工作目录环境变量
      PWD: options?.cwd ? this.resolvePath(options.cwd) : this.workdir,
    } as Record<string, string>;
  }

  /**
   * 执行进程
   *
   * 使用 Bun.spawn 执行命令，支持超时控制和进程跟踪
   */
  private async spawnProcess(
    args: string[],
    options?: ExecutionOptions
  ): Promise<Omit<ExecutionResult, 'duration'>> {
    const timeout = options?.timeout ?? this.config.timeout;
    const cwd = options?.cwd ? this.resolvePath(options.cwd) : this.workdir;
    const env = this.buildEnv(options);

    // 验证工作目录
    await this.validatePathWithRealpath(cwd);

    return new Promise((resolve, reject) => {
      let timedOut = false;
      let timer: ReturnType<typeof setTimeout> | undefined;

      try {
        // 使用 Bun.spawn 执行
        const proc = Bun.spawn(args, {
          cwd,
          env,
          stdin: options?.stdin ? new Blob([options.stdin]) : undefined,
          stdout: 'pipe',
          stderr: 'pipe',
        });

        // 跟踪活跃进程
        this.activeProcesses.add(proc);

        // 设置超时计时器
        timer = setTimeout(() => {
          timedOut = true;
          proc.kill();
          this.activeProcesses.delete(proc);
          reject(new TimeoutError(timeout));
        }, timeout);

        // 等待进程完成
        proc.exited.then(async (exitCode) => {
          this.activeProcesses.delete(proc);

          if (timedOut) {
            return; // 已经被超时处理
          }

          clearTimeout(timer);

          // 读取输出
          const stdout = await new Response(proc.stdout).text();
          const stderr = await new Response(proc.stderr).text();

          resolve({
            success: exitCode === 0,
            stdout,
            stderr,
            exitCode,
            timedOut: false,
          });
        }).catch((error) => {
          this.activeProcesses.delete(proc);

          if (timedOut) {
            return; // 已经被超时处理
          }

          clearTimeout(timer);
          reject(error);
        });
      } catch (error) {
        if (timer) {
          clearTimeout(timer);
        }
        reject(error);
      }
    });
  }
}

// ============================================================================
// 工厂函数
// ============================================================================

/**
 * 创建本地沙盒实例
 *
 * @param id - 沙盒 ID（可选，自动生成）
 * @param config - 沙盒配置
 * @returns LocalSandbox 实例
 *
 * @example
 * ```ts
 * const sandbox = await createLocalSandbox('test-001', config);
 * await sandbox.initialize();
 * ```
 */
export function createLocalSandbox(
  id: string | undefined,
  config: SandboxConfig
): LocalSandbox {
  return new LocalSandbox(id, config);
}
